### ISSUE TITLE
Mistake in merge conflict resolve

### ISSUE THREAD

**Issue by yuichiok** [QQbarAnalysis/QQbarAnalysis#19]
Hi @airqui 

Couple days ago, I merged upstream/QQbarAnalysis2021 to my forked repo.
But now I realized there was a mistake because I couldn't compile the processors.
The mistake was solved by changing following line back to what it was.
`write=WritePFOInfo(evt,component,pfo_recorded,2,0,_colName, _versionPID);`

Essentially I am paranoid that there were other lines that I didn't resolve correctly, even though it's working fine on the surface. Shall I make a pull request so you can check my mistake in the merge conflict, or perhaps there's a simpler way?

Cheers

**Comment by airqui** [comment]
Hi @yuichiok 
You can do almost everything with gi but I never know the right command...

I have the latest version and I do not have any issue of compilation.

Could you try to pull (in the terminal, in the folder where you have our private fork) from the main repository?
`git remote add new_origin https://github.com/QQbarAnalysis/QQbarAnalysis`
`git pull new_origin QQbarAnalysis2021`

**Comment by airqui** [comment]
I am not sure if this will erase/overwrite any other change that you may have done in the analysis.... this is why I prefer to keep in the main repository only a couple of "standard" analysis

**Comment by airqui** [comment]
You may also try 
`git checkout new_origin/QQbarAnalysis2021 <path to file>`  after defining new_origin and path to file I guess that it is src/QQbarAnalysis.cc

**Comment by yuichiok** [comment]
Thank you.
I did it and all it said was `Already up-to-date.` so I believe there was no other mistake.

**Comment by airqui** [comment]
@yuichiok maybe try to compare the files "by hand", but anyway...
